server:
  port: 7749
  servlet:
    context-path: /api

spring:
  profiles:
    include: storage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://121.36.6.81:3306/blog?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: 114092
    hikari:
      max-lifetime: 120000

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy=org:
          hibernate:
            boot:
              model:
                naming:
                  PhysicalNamingStrategyStandardImpl  # 设置驼峰转换
    show-sql: false
    open-in-view: false # 避免open-inview警告